// This file is autogenerated, do not edit

@_implementationOnly import GDExtension

public class Nil {
    // Contains a binary blob where this type information is stored
    public var content: ContentType = 0
    // Used to initialize empty types
    public static let zero: ContentType  = 0
    // Convenience type that matches the build configuration storage needs
    public typealias ContentType = Int32
    // Used to construct objects on virtual proxies
    public required init (content: ContentType) {
        var copy = content
        var args: [UnsafeRawPointer?] = []
        withUnsafePointer (to: &copy) { ptr in
            args.append (ptr)
            Nil.constructor1 (&self.content, &args)
        }
        
    }
    
    static var constructor0: GDExtensionPtrConstructor = gi.variant_get_ptr_constructor (GDEXTENSION_VARIANT_TYPE_NIL, 0)!
    
    public required init () {
        Nil.constructor0 (&content, nil)
    }
    
    static var constructor1: GDExtensionPtrConstructor = gi.variant_get_ptr_constructor (GDEXTENSION_VARIANT_TYPE_NIL, 1)!
    
    public init (from: Variant) {
        var args: [UnsafeRawPointer?] = []
        withUnsafePointer (to: &from.content) { p0 in
            args.append (p0)
        
            Nil.constructor1 (&content, &args)
        }
    }
    
    static var operator_4: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_BOOL)!
    }()
    
    public static func == (lhs: Nil, rhs: Bool) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_4 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_5: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_BOOL)!
    }()
    
    public static func != (lhs: Nil, rhs: Bool) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_5 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_6: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_AND, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_BOOL)!
    }()
    
    public static func && (lhs: Nil, rhs: Bool) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_6 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_7: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_AND, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_BOOL)!
    }()
    
    public static func || (lhs: Nil, rhs: Bool) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_7 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_9: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_INT)!
    }()
    
    public static func == (lhs: Nil, rhs: Int64) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_9 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_10: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_INT)!
    }()
    
    public static func != (lhs: Nil, rhs: Int64) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_10 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_11: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_AND, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_INT)!
    }()
    
    public static func && (lhs: Nil, rhs: Int64) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_11 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_12: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_AND, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_INT)!
    }()
    
    public static func || (lhs: Nil, rhs: Int64) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_12 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_14: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_FLOAT)!
    }()
    
    public static func == (lhs: Nil, rhs: Double) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = Double (rhs)
        
        Nil.operator_14 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_15: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_FLOAT)!
    }()
    
    public static func != (lhs: Nil, rhs: Double) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = Double (rhs)
        
        Nil.operator_15 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_16: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_AND, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_FLOAT)!
    }()
    
    public static func && (lhs: Nil, rhs: Double) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = Double (rhs)
        
        Nil.operator_16 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_17: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_AND, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_FLOAT)!
    }()
    
    public static func || (lhs: Nil, rhs: Double) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = Double (rhs)
        
        Nil.operator_17 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_19: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_STRING)!
    }()
    
    public static func == (lhs: Nil, rhs: String) -> Bool  {
        var result: Bool = Bool()
        let gstr_rhs = GString (rhs)
        
        Nil.operator_19 (&lhs.content, &gstr_rhs.content, &result)
        return result
    }
    
    static var operator_20: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_STRING)!
    }()
    
    public static func != (lhs: Nil, rhs: String) -> Bool  {
        var result: Bool = Bool()
        let gstr_rhs = GString (rhs)
        
        Nil.operator_20 (&lhs.content, &gstr_rhs.content, &result)
        return result
    }
    
    static var operator_21: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_VECTOR2)!
    }()
    
    public static func == (lhs: Nil, rhs: Vector2) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_21 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_22: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_VECTOR2)!
    }()
    
    public static func != (lhs: Nil, rhs: Vector2) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_22 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_23: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_VECTOR2I)!
    }()
    
    public static func == (lhs: Nil, rhs: Vector2i) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_23 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_24: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_VECTOR2I)!
    }()
    
    public static func != (lhs: Nil, rhs: Vector2i) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_24 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_25: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_RECT2)!
    }()
    
    public static func == (lhs: Nil, rhs: Rect2) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_25 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_26: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_RECT2)!
    }()
    
    public static func != (lhs: Nil, rhs: Rect2) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_26 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_27: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_RECT2I)!
    }()
    
    public static func == (lhs: Nil, rhs: Rect2i) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_27 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_28: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_RECT2I)!
    }()
    
    public static func != (lhs: Nil, rhs: Rect2i) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_28 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_29: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_VECTOR3)!
    }()
    
    public static func == (lhs: Nil, rhs: Vector3) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_29 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_30: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_VECTOR3)!
    }()
    
    public static func != (lhs: Nil, rhs: Vector3) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_30 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_31: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_VECTOR3I)!
    }()
    
    public static func == (lhs: Nil, rhs: Vector3i) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_31 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_32: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_VECTOR3I)!
    }()
    
    public static func != (lhs: Nil, rhs: Vector3i) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_32 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_33: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_TRANSFORM2D)!
    }()
    
    public static func == (lhs: Nil, rhs: Transform2D) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_33 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_34: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_TRANSFORM2D)!
    }()
    
    public static func != (lhs: Nil, rhs: Transform2D) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_34 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_35: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_VECTOR4)!
    }()
    
    public static func == (lhs: Nil, rhs: Vector4) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_35 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_36: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_VECTOR4)!
    }()
    
    public static func != (lhs: Nil, rhs: Vector4) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_36 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_37: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_VECTOR4I)!
    }()
    
    public static func == (lhs: Nil, rhs: Vector4i) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_37 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_38: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_VECTOR4I)!
    }()
    
    public static func != (lhs: Nil, rhs: Vector4i) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_38 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_39: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PLANE)!
    }()
    
    public static func == (lhs: Nil, rhs: Plane) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_39 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_40: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PLANE)!
    }()
    
    public static func != (lhs: Nil, rhs: Plane) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_40 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_41: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_QUATERNION)!
    }()
    
    public static func == (lhs: Nil, rhs: Quaternion) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_41 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_42: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_QUATERNION)!
    }()
    
    public static func != (lhs: Nil, rhs: Quaternion) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_42 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_43: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_AABB)!
    }()
    
    public static func == (lhs: Nil, rhs: AABB) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_43 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_44: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_AABB)!
    }()
    
    public static func != (lhs: Nil, rhs: AABB) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_44 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_45: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_BASIS)!
    }()
    
    public static func == (lhs: Nil, rhs: Basis) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_45 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_46: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_BASIS)!
    }()
    
    public static func != (lhs: Nil, rhs: Basis) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_46 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_47: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_TRANSFORM3D)!
    }()
    
    public static func == (lhs: Nil, rhs: Transform3D) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_47 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_48: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_TRANSFORM3D)!
    }()
    
    public static func != (lhs: Nil, rhs: Transform3D) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_48 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_49: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PROJECTION)!
    }()
    
    public static func == (lhs: Nil, rhs: Projection) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_49 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_50: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PROJECTION)!
    }()
    
    public static func != (lhs: Nil, rhs: Projection) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_50 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_51: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_COLOR)!
    }()
    
    public static func == (lhs: Nil, rhs: Color) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_51 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_52: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_COLOR)!
    }()
    
    public static func != (lhs: Nil, rhs: Color) -> Bool  {
        var result: Bool = Bool()
        var copy_rhs = rhs
        
        Nil.operator_52 (&lhs.content, &copy_rhs, &result)
        return result
    }
    
    static var operator_53: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_STRING_NAME)!
    }()
    
    public static func == (lhs: Nil, rhs: StringName) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_53 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_54: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_STRING_NAME)!
    }()
    
    public static func != (lhs: Nil, rhs: StringName) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_54 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_55: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_NODE_PATH)!
    }()
    
    public static func == (lhs: Nil, rhs: NodePath) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_55 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_56: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_NODE_PATH)!
    }()
    
    public static func != (lhs: Nil, rhs: NodePath) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_56 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_57: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_RID)!
    }()
    
    public static func == (lhs: Nil, rhs: RID) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_57 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_58: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_RID)!
    }()
    
    public static func != (lhs: Nil, rhs: RID) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_58 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_59: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_OBJECT)!
    }()
    
    public static func == (lhs: Nil, rhs: Object) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_59 (&lhs.content, &rhs.handle, &result)
        return result
    }
    
    static var operator_60: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_OBJECT)!
    }()
    
    public static func != (lhs: Nil, rhs: Object) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_60 (&lhs.content, &rhs.handle, &result)
        return result
    }
    
    static var operator_61: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_AND, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_OBJECT)!
    }()
    
    public static func && (lhs: Nil, rhs: Object) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_61 (&lhs.content, &rhs.handle, &result)
        return result
    }
    
    static var operator_62: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_AND, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_OBJECT)!
    }()
    
    public static func || (lhs: Nil, rhs: Object) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_62 (&lhs.content, &rhs.handle, &result)
        return result
    }
    
    static var operator_64: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_CALLABLE)!
    }()
    
    public static func == (lhs: Nil, rhs: Callable) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_64 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_65: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_CALLABLE)!
    }()
    
    public static func != (lhs: Nil, rhs: Callable) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_65 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_66: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_SIGNAL)!
    }()
    
    public static func == (lhs: Nil, rhs: Signal) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_66 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_67: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_SIGNAL)!
    }()
    
    public static func != (lhs: Nil, rhs: Signal) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_67 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_68: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_DICTIONARY)!
    }()
    
    public static func == (lhs: Nil, rhs: GDictionary) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_68 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_69: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_DICTIONARY)!
    }()
    
    public static func != (lhs: Nil, rhs: GDictionary) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_69 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_71: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_ARRAY)!
    }()
    
    public static func == (lhs: Nil, rhs: GArray) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_71 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_72: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_ARRAY)!
    }()
    
    public static func != (lhs: Nil, rhs: GArray) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_72 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_74: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PACKED_BYTE_ARRAY)!
    }()
    
    public static func == (lhs: Nil, rhs: PackedByteArray) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_74 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_75: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PACKED_BYTE_ARRAY)!
    }()
    
    public static func != (lhs: Nil, rhs: PackedByteArray) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_75 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_76: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PACKED_INT32_ARRAY)!
    }()
    
    public static func == (lhs: Nil, rhs: PackedInt32Array) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_76 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_77: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PACKED_INT32_ARRAY)!
    }()
    
    public static func != (lhs: Nil, rhs: PackedInt32Array) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_77 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_78: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PACKED_INT64_ARRAY)!
    }()
    
    public static func == (lhs: Nil, rhs: PackedInt64Array) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_78 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_79: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PACKED_INT64_ARRAY)!
    }()
    
    public static func != (lhs: Nil, rhs: PackedInt64Array) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_79 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_80: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT32_ARRAY)!
    }()
    
    public static func == (lhs: Nil, rhs: PackedFloat32Array) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_80 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_81: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT32_ARRAY)!
    }()
    
    public static func != (lhs: Nil, rhs: PackedFloat32Array) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_81 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_82: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT64_ARRAY)!
    }()
    
    public static func == (lhs: Nil, rhs: PackedFloat64Array) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_82 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_83: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT64_ARRAY)!
    }()
    
    public static func != (lhs: Nil, rhs: PackedFloat64Array) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_83 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_84: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PACKED_STRING_ARRAY)!
    }()
    
    public static func == (lhs: Nil, rhs: PackedStringArray) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_84 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_85: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PACKED_STRING_ARRAY)!
    }()
    
    public static func != (lhs: Nil, rhs: PackedStringArray) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_85 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_86: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR2_ARRAY)!
    }()
    
    public static func == (lhs: Nil, rhs: PackedVector2Array) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_86 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_87: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR2_ARRAY)!
    }()
    
    public static func != (lhs: Nil, rhs: PackedVector2Array) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_87 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_88: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR3_ARRAY)!
    }()
    
    public static func == (lhs: Nil, rhs: PackedVector3Array) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_88 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_89: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR3_ARRAY)!
    }()
    
    public static func != (lhs: Nil, rhs: PackedVector3Array) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_89 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_90: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PACKED_COLOR_ARRAY)!
    }()
    
    public static func == (lhs: Nil, rhs: PackedColorArray) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_90 (&lhs.content, &rhs.content, &result)
        return result
    }
    
    static var operator_91: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_NIL, GDEXTENSION_VARIANT_TYPE_PACKED_COLOR_ARRAY)!
    }()
    
    public static func != (lhs: Nil, rhs: PackedColorArray) -> Bool  {
        var result: Bool = Bool()
        
        Nil.operator_91 (&lhs.content, &rhs.content, &result)
        return result
    }
    
}

