// This file is autogenerated, do not edit

@_implementationOnly import GDExtension

/// A 4D vector using floating point coordinates.
/// 
/// A 4-element structure that can be used to represent 4D coordinates or any other quadruplet of numeric values.
/// 
/// It uses floating-point coordinates. By default, these floating-point values use 32-bit precision, unlike float which is always 64-bit. If double precision is needed, compile the engine with the option `precision=double`.
/// 
/// See ``Vector4i`` for its integer counterpart.
/// 
/// > Note: In a boolean context, a Vector4 will evaluate to `false` if it's equal to `Vector4(0, 0, 0, 0)`. Otherwise, a Vector4 will always evaluate to `true`.
/// 
public struct Vector4: Equatable, Hashable {
    /// The vector's X component. Also accessible by using the index position `[0]`.
    public var x: Float
    /// The vector's Y component. Also accessible by using the index position `[1]`.
    public var y: Float
    /// The vector's Z component. Also accessible by using the index position `[2]`.
    public var z: Float
    /// The vector's W component. Also accessible by using the index position `[3]`.
    public var w: Float
    public enum Axis: Int64 {
        /// Enumerated value for the X axis. Returned by ``maxAxisIndex()`` and ``minAxisIndex()``.
        case x = 0 // AXIS_X
        /// Enumerated value for the Y axis. Returned by ``maxAxisIndex()`` and ``minAxisIndex()``.
        case y = 1 // AXIS_Y
        /// Enumerated value for the Z axis. Returned by ``maxAxisIndex()`` and ``minAxisIndex()``.
        case z = 2 // AXIS_Z
        /// Enumerated value for the W axis. Returned by ``maxAxisIndex()`` and ``minAxisIndex()``.
        case w = 3 // AXIS_W
    }
    
    static var constructor0: GDExtensionPtrConstructor = gi.variant_get_ptr_constructor (GDEXTENSION_VARIANT_TYPE_VECTOR4, 0)!
    
    /// Constructs a default-initialized ``Vector4`` with all components set to `0`.
    public init () {
        self.x = Float ()
        self.y = Float ()
        self.z = Float ()
        self.w = Float ()
    }
    
    static var constructor1: GDExtensionPtrConstructor = gi.variant_get_ptr_constructor (GDEXTENSION_VARIANT_TYPE_VECTOR4, 1)!
    
    /// Constructs a ``Vector4`` as a copy of the given ``Vector4``.
    public init (from: Vector4) {
        self.x = Float ()
        self.y = Float ()
        self.z = Float ()
        self.w = Float ()
        var copy_from = from
        var args: [UnsafeRawPointer?] = []
        withUnsafePointer (to: &copy_from) { p0 in
            args.append (p0)
        
            Vector4.constructor1 (&self, &args)
        }
    }
    
    static var constructor2: GDExtensionPtrConstructor = gi.variant_get_ptr_constructor (GDEXTENSION_VARIANT_TYPE_VECTOR4, 2)!
    
    /// Constructs a new ``Vector4`` from the given ``Vector4i``.
    public init (from: Vector4i) {
        self.x = Float ()
        self.y = Float ()
        self.z = Float ()
        self.w = Float ()
        var copy_from = from
        var args: [UnsafeRawPointer?] = []
        withUnsafePointer (to: &copy_from) { p0 in
            args.append (p0)
        
            Vector4.constructor2 (&self, &args)
        }
    }
    
    static var constructor3: GDExtensionPtrConstructor = gi.variant_get_ptr_constructor (GDEXTENSION_VARIANT_TYPE_VECTOR4, 3)!
    
    /// Returns a ``Vector4`` with the given components.
    public init (x: Float, y: Float, z: Float, w: Float) {
        self.x = x
        self.y = y
        self.z = z
        self.w = w
    }
    
    
    /* Methods */
    
    static var method_min_axis_index: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("min_axis_index")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 3173160232)!
    }()
    
    /// Returns the axis of the vector's lowest value. See `AXIS_*` constants. If all components are equal, this method returns .w.
    public func minAxisIndex ()-> Int64 {
        var result: Int64 = Int64()
        withUnsafePointer (to: self) { ptr in 
            Vector4.method_min_axis_index (UnsafeMutableRawPointer (mutating: ptr), nil, &result, 0)
        }
        return result
    }
    
    static var method_max_axis_index: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("max_axis_index")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 3173160232)!
    }()
    
    /// Returns the axis of the vector's highest value. See `AXIS_*` constants. If all components are equal, this method returns .x.
    public func maxAxisIndex ()-> Int64 {
        var result: Int64 = Int64()
        withUnsafePointer (to: self) { ptr in 
            Vector4.method_max_axis_index (UnsafeMutableRawPointer (mutating: ptr), nil, &result, 0)
        }
        return result
    }
    
    static var method_length: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("length")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 466405837)!
    }()
    
    /// Returns the length (magnitude) of this vector.
    public func length ()-> Double {
        var result: Double = Double()
        withUnsafePointer (to: self) { ptr in 
            Vector4.method_length (UnsafeMutableRawPointer (mutating: ptr), nil, &result, 0)
        }
        return result
    }
    
    static var method_length_squared: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("length_squared")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 466405837)!
    }()
    
    /// Returns the squared length (squared magnitude) of this vector.
    /// 
    /// This method runs faster than ``length()``, so prefer it if you need to compare vectors or need the squared distance for some formula.
    /// 
    public func lengthSquared ()-> Double {
        var result: Double = Double()
        withUnsafePointer (to: self) { ptr in 
            Vector4.method_length_squared (UnsafeMutableRawPointer (mutating: ptr), nil, &result, 0)
        }
        return result
    }
    
    static var method_abs: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("abs")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 80860099)!
    }()
    
    /// Returns a new vector with all components in absolute values (i.e. positive).
    public func abs ()-> Vector4 {
        var result: Vector4 = Vector4()
        withUnsafePointer (to: self) { ptr in 
            Vector4.method_abs (UnsafeMutableRawPointer (mutating: ptr), nil, &result, 0)
        }
        return result
    }
    
    static var method_sign: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("sign")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 80860099)!
    }()
    
    /// Returns a new vector with each component set to `1.0` if it's positive, `-1.0` if it's negative, and `0.0` if it's zero. The result is identical to calling ``@GlobalScope.sign`` on each component.
    public func sign ()-> Vector4 {
        var result: Vector4 = Vector4()
        withUnsafePointer (to: self) { ptr in 
            Vector4.method_sign (UnsafeMutableRawPointer (mutating: ptr), nil, &result, 0)
        }
        return result
    }
    
    static var method_floor: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("floor")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 80860099)!
    }()
    
    /// Returns a new vector with all components rounded down (towards negative infinity).
    public func floor ()-> Vector4 {
        var result: Vector4 = Vector4()
        withUnsafePointer (to: self) { ptr in 
            Vector4.method_floor (UnsafeMutableRawPointer (mutating: ptr), nil, &result, 0)
        }
        return result
    }
    
    static var method_ceil: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("ceil")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 80860099)!
    }()
    
    /// Returns a new vector with all components rounded up (towards positive infinity).
    public func ceil ()-> Vector4 {
        var result: Vector4 = Vector4()
        withUnsafePointer (to: self) { ptr in 
            Vector4.method_ceil (UnsafeMutableRawPointer (mutating: ptr), nil, &result, 0)
        }
        return result
    }
    
    static var method_round: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("round")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 80860099)!
    }()
    
    /// Returns a new vector with all components rounded to the nearest integer, with halfway cases rounded away from zero.
    public func round ()-> Vector4 {
        var result: Vector4 = Vector4()
        withUnsafePointer (to: self) { ptr in 
            Vector4.method_round (UnsafeMutableRawPointer (mutating: ptr), nil, &result, 0)
        }
        return result
    }
    
    static var method_cubic_interpolate: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("cubic_interpolate")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 726768410)!
    }()
    
    /// Performs a cubic interpolation between this vector and `b` using `preA` and `postB` as handles, and returns the result at position `weight`. `weight` is on the range of 0.0 to 1.0, representing the amount of interpolation.
    public func cubicInterpolate (b: Vector4, preA: Vector4, postB: Vector4, weight: Double)-> Vector4 {
        var result: Vector4 = Vector4()
        var copy_b = b
        var copy_pre_a = preA
        var copy_post_b = postB
        var copy_weight = Double (weight)
        var args: [UnsafeRawPointer?] = []
        return withUnsafePointer (to: &copy_b) { p0 in
            args.append (p0)
            return withUnsafePointer (to: &copy_pre_a) { p1 in
                args.append (p1)
                return withUnsafePointer (to: &copy_post_b) { p2 in
                    args.append (p2)
                    return withUnsafePointer (to: &copy_weight) { p3 in
                        args.append (p3)
        
                        withUnsafePointer (to: self) { ptr in 
                            Vector4.method_cubic_interpolate (UnsafeMutableRawPointer (mutating: ptr), &args, &result, 4)
                        }
                        return result
                    }
                }
            }
        }
    }
    
    static var method_cubic_interpolate_in_time: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("cubic_interpolate_in_time")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 681631873)!
    }()
    
    /// Performs a cubic interpolation between this vector and `b` using `preA` and `postB` as handles, and returns the result at position `weight`. `weight` is on the range of 0.0 to 1.0, representing the amount of interpolation.
    /// 
    /// It can perform smoother interpolation than ``cubicInterpolate(b:preA:postB:weight:)`` by the time values.
    /// 
    public func cubicInterpolateInTime (b: Vector4, preA: Vector4, postB: Vector4, weight: Double, bT: Double, preAT: Double, postBT: Double)-> Vector4 {
        var result: Vector4 = Vector4()
        var copy_b = b
        var copy_pre_a = preA
        var copy_post_b = postB
        var copy_weight = Double (weight)
        var copy_b_t = Double (bT)
        var copy_pre_a_t = Double (preAT)
        var copy_post_b_t = Double (postBT)
        var args: [UnsafeRawPointer?] = []
        return withUnsafePointer (to: &copy_b) { p0 in
            args.append (p0)
            return withUnsafePointer (to: &copy_pre_a) { p1 in
                args.append (p1)
                return withUnsafePointer (to: &copy_post_b) { p2 in
                    args.append (p2)
                    return withUnsafePointer (to: &copy_weight) { p3 in
                        args.append (p3)
                        return withUnsafePointer (to: &copy_b_t) { p4 in
                            args.append (p4)
                            return withUnsafePointer (to: &copy_pre_a_t) { p5 in
                                args.append (p5)
                                return withUnsafePointer (to: &copy_post_b_t) { p6 in
                                    args.append (p6)
        
                                    withUnsafePointer (to: self) { ptr in 
                                        Vector4.method_cubic_interpolate_in_time (UnsafeMutableRawPointer (mutating: ptr), &args, &result, 7)
                                    }
                                    return result
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    
    static var method_posmod: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("posmod")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 3129671720)!
    }()
    
    /// Returns a vector composed of the ``@GlobalScope.fposmod`` of this vector's components and `mod`.
    public func posmod (mod: Double)-> Vector4 {
        var result: Vector4 = Vector4()
        var copy_mod = Double (mod)
        var args: [UnsafeRawPointer?] = []
        return withUnsafePointer (to: &copy_mod) { p0 in
            args.append (p0)
        
            withUnsafePointer (to: self) { ptr in 
                Vector4.method_posmod (UnsafeMutableRawPointer (mutating: ptr), &args, &result, 1)
            }
            return result
        }
    }
    
    static var method_posmodv: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("posmodv")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 2031281584)!
    }()
    
    /// Returns a vector composed of the ``@GlobalScope.fposmod`` of this vector's components and `modv`'s components.
    public func posmodv (modv: Vector4)-> Vector4 {
        var result: Vector4 = Vector4()
        var copy_modv = modv
        var args: [UnsafeRawPointer?] = []
        return withUnsafePointer (to: &copy_modv) { p0 in
            args.append (p0)
        
            withUnsafePointer (to: self) { ptr in 
                Vector4.method_posmodv (UnsafeMutableRawPointer (mutating: ptr), &args, &result, 1)
            }
            return result
        }
    }
    
    static var method_clamp: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("clamp")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 823915692)!
    }()
    
    /// Returns a new vector with all components clamped between the components of `min` and `max`, by running ``@GlobalScope.clamp`` on each component.
    public func clamp (min: Vector4, max: Vector4)-> Vector4 {
        var result: Vector4 = Vector4()
        var copy_min = min
        var copy_max = max
        var args: [UnsafeRawPointer?] = []
        return withUnsafePointer (to: &copy_min) { p0 in
            args.append (p0)
            return withUnsafePointer (to: &copy_max) { p1 in
                args.append (p1)
        
                withUnsafePointer (to: self) { ptr in 
                    Vector4.method_clamp (UnsafeMutableRawPointer (mutating: ptr), &args, &result, 2)
                }
                return result
            }
        }
    }
    
    static var method_normalized: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("normalized")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 80860099)!
    }()
    
    /// Returns the result of scaling the vector to unit length. Equivalent to `v / v.length()`. See also ``isNormalized()``.
    /// 
    /// > Note: This function may return incorrect values if the input vector length is near zero.
    /// 
    public func normalized ()-> Vector4 {
        var result: Vector4 = Vector4()
        withUnsafePointer (to: self) { ptr in 
            Vector4.method_normalized (UnsafeMutableRawPointer (mutating: ptr), nil, &result, 0)
        }
        return result
    }
    
    static var method_is_normalized: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("is_normalized")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 3918633141)!
    }()
    
    /// Returns `true` if the vector is normalized, i.e. its length is approximately equal to 1.
    public func isNormalized ()-> Bool {
        var result: Bool = Bool()
        withUnsafePointer (to: self) { ptr in 
            Vector4.method_is_normalized (UnsafeMutableRawPointer (mutating: ptr), nil, &result, 0)
        }
        return result
    }
    
    static var method_direction_to: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("direction_to")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 2031281584)!
    }()
    
    /// Returns the normalized vector pointing from this vector to `to`. This is equivalent to using `(b - a).normalized()`.
    public func directionTo (_ to: Vector4)-> Vector4 {
        var result: Vector4 = Vector4()
        var copy_to = to
        var args: [UnsafeRawPointer?] = []
        return withUnsafePointer (to: &copy_to) { p0 in
            args.append (p0)
        
            withUnsafePointer (to: self) { ptr in 
                Vector4.method_direction_to (UnsafeMutableRawPointer (mutating: ptr), &args, &result, 1)
            }
            return result
        }
    }
    
    static var method_distance_to: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("distance_to")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 3770801042)!
    }()
    
    /// Returns the distance between this vector and `to`.
    public func distanceTo (_ to: Vector4)-> Double {
        var result: Double = Double()
        var copy_to = to
        var args: [UnsafeRawPointer?] = []
        return withUnsafePointer (to: &copy_to) { p0 in
            args.append (p0)
        
            withUnsafePointer (to: self) { ptr in 
                Vector4.method_distance_to (UnsafeMutableRawPointer (mutating: ptr), &args, &result, 1)
            }
            return result
        }
    }
    
    static var method_distance_squared_to: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("distance_squared_to")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 3770801042)!
    }()
    
    /// Returns the squared distance between this vector and `to`.
    /// 
    /// This method runs faster than ``distanceTo(to:)``, so prefer it if you need to compare vectors or need the squared distance for some formula.
    /// 
    public func distanceSquaredTo (_ to: Vector4)-> Double {
        var result: Double = Double()
        var copy_to = to
        var args: [UnsafeRawPointer?] = []
        return withUnsafePointer (to: &copy_to) { p0 in
            args.append (p0)
        
            withUnsafePointer (to: self) { ptr in 
                Vector4.method_distance_squared_to (UnsafeMutableRawPointer (mutating: ptr), &args, &result, 1)
            }
            return result
        }
    }
    
    static var method_dot: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("dot")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 3770801042)!
    }()
    
    /// Returns the dot product of this vector and `with`.
    public func dot (with: Vector4)-> Double {
        var result: Double = Double()
        var copy_with = with
        var args: [UnsafeRawPointer?] = []
        return withUnsafePointer (to: &copy_with) { p0 in
            args.append (p0)
        
            withUnsafePointer (to: self) { ptr in 
                Vector4.method_dot (UnsafeMutableRawPointer (mutating: ptr), &args, &result, 1)
            }
            return result
        }
    }
    
    static var method_inverse: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("inverse")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 80860099)!
    }()
    
    /// Returns the inverse of the vector. This is the same as `Vector4(1.0 / v.x, 1.0 / v.y, 1.0 / v.z, 1.0 / v.w)`.
    public func inverse ()-> Vector4 {
        var result: Vector4 = Vector4()
        withUnsafePointer (to: self) { ptr in 
            Vector4.method_inverse (UnsafeMutableRawPointer (mutating: ptr), nil, &result, 0)
        }
        return result
    }
    
    static var method_is_equal_approx: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("is_equal_approx")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 88913544)!
    }()
    
    /// Returns `true` if this vector and `to` are approximately equal, by running ``@GlobalScope.is_equal_approx`` on each component.
    public func isEqualApprox (to: Vector4)-> Bool {
        var result: Bool = Bool()
        var copy_to = to
        var args: [UnsafeRawPointer?] = []
        return withUnsafePointer (to: &copy_to) { p0 in
            args.append (p0)
        
            withUnsafePointer (to: self) { ptr in 
                Vector4.method_is_equal_approx (UnsafeMutableRawPointer (mutating: ptr), &args, &result, 1)
            }
            return result
        }
    }
    
    static var method_is_zero_approx: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("is_zero_approx")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 3918633141)!
    }()
    
    /// Returns `true` if this vector's values are approximately zero, by running ``@GlobalScope.is_zero_approx`` on each component.
    /// 
    /// This method is faster than using ``isEqualApprox(to:)`` with one value as a zero vector.
    /// 
    public func isZeroApprox ()-> Bool {
        var result: Bool = Bool()
        withUnsafePointer (to: self) { ptr in 
            Vector4.method_is_zero_approx (UnsafeMutableRawPointer (mutating: ptr), nil, &result, 0)
        }
        return result
    }
    
    static var method_is_finite: GDExtensionPtrBuiltInMethod = {
        let name = StringName ("is_finite")
        return gi.variant_get_ptr_builtin_method (GDEXTENSION_VARIANT_TYPE_VECTOR4, &name.content, 3918633141)!
    }()
    
    /// Returns `true` if this vector is finite, by calling ``@GlobalScope.is_finite`` on each component.
    public func isFinite ()-> Bool {
        var result: Bool = Bool()
        withUnsafePointer (to: self) { ptr in 
            Vector4.method_is_finite (UnsafeMutableRawPointer (mutating: ptr), nil, &result, 0)
        }
        return result
    }
    
    private static var indexed_getter: GDExtensionPtrIndexedGetter = {
        return gi.variant_get_ptr_indexed_getter (GDEXTENSION_VARIANT_TYPE_VECTOR4)!
    }()
    
    private static var indexed_setter: GDExtensionPtrIndexedSetter = {
        return gi.variant_get_ptr_indexed_setter (GDEXTENSION_VARIANT_TYPE_VECTOR4)!
    }()
    
     public subscript (index: Int64) -> Double {
        mutating get {
            var result = Double ()
            Self.indexed_getter (&self, index, &result)
            return result
        }
        
        set {
            var value = newValue
            Self.indexed_setter (&self, index, &value)
        }
        
    }
    
    static var operator_5: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_MULTIPLY, GDEXTENSION_VARIANT_TYPE_VECTOR4, GDEXTENSION_VARIANT_TYPE_INT)!
    }()
    
    /// Multiplies each component of the ``Vector4`` by the given integer.
    public static func * (lhs: Vector4, rhs: Int64) -> Vector4  {
        var result: Vector4 = Vector4()
        var copy_lhs = lhs
        var copy_rhs = rhs
        
        Vector4.operator_5 (&copy_lhs, &copy_rhs, &result)
        return result
    }
    
    static var operator_6: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_DIVIDE, GDEXTENSION_VARIANT_TYPE_VECTOR4, GDEXTENSION_VARIANT_TYPE_INT)!
    }()
    
    /// Divides each component of the ``Vector4`` by the given integer.
    public static func / (lhs: Vector4, rhs: Int64) -> Vector4  {
        var result: Vector4 = Vector4()
        var copy_lhs = lhs
        var copy_rhs = rhs
        
        Vector4.operator_6 (&copy_lhs, &copy_rhs, &result)
        return result
    }
    
    static var operator_7: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_MULTIPLY, GDEXTENSION_VARIANT_TYPE_VECTOR4, GDEXTENSION_VARIANT_TYPE_FLOAT)!
    }()
    
    /// Multiplies each component of the ``Vector4`` by the given integer.
    public static func * (lhs: Vector4, rhs: Double) -> Vector4  {
        var result: Vector4 = Vector4()
        var copy_lhs = lhs
        var copy_rhs = Double (rhs)
        
        Vector4.operator_7 (&copy_lhs, &copy_rhs, &result)
        return result
    }
    
    static var operator_8: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_DIVIDE, GDEXTENSION_VARIANT_TYPE_VECTOR4, GDEXTENSION_VARIANT_TYPE_FLOAT)!
    }()
    
    /// Divides each component of the ``Vector4`` by the given integer.
    public static func / (lhs: Vector4, rhs: Double) -> Vector4  {
        var result: Vector4 = Vector4()
        var copy_lhs = lhs
        var copy_rhs = Double (rhs)
        
        Vector4.operator_8 (&copy_lhs, &copy_rhs, &result)
        return result
    }
    
    static var operator_9: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_EQUAL, GDEXTENSION_VARIANT_TYPE_VECTOR4, GDEXTENSION_VARIANT_TYPE_VECTOR4)!
    }()
    
    /// Returns `true` if the vectors are exactly equal.
    /// 
    /// > Note: Due to floating-point precision errors, consider using ``isEqualApprox(to:)`` instead, which is more reliable.
    /// 
    /// > Note: Vectors with ``@GDScript.NAN`` elements don't behave the same as other vectors. Therefore, the results from this operator may not be accurate if NaNs are included.
    /// 
    public static func == (lhs: Vector4, rhs: Vector4) -> Bool  {
        var result: Bool = Bool()
        var copy_lhs = lhs
        var copy_rhs = rhs
        
        Vector4.operator_9 (&copy_lhs, &copy_rhs, &result)
        return result
    }
    
    static var operator_10: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_NOT_EQUAL, GDEXTENSION_VARIANT_TYPE_VECTOR4, GDEXTENSION_VARIANT_TYPE_VECTOR4)!
    }()
    
    /// Returns `true` if the vectors are not equal.
    /// 
    /// > Note: Due to floating-point precision errors, consider using ``isEqualApprox(to:)`` instead, which is more reliable.
    /// 
    /// > Note: Vectors with ``@GDScript.NAN`` elements don't behave the same as other vectors. Therefore, the results from this operator may not be accurate if NaNs are included.
    /// 
    public static func != (lhs: Vector4, rhs: Vector4) -> Bool  {
        var result: Bool = Bool()
        var copy_lhs = lhs
        var copy_rhs = rhs
        
        Vector4.operator_10 (&copy_lhs, &copy_rhs, &result)
        return result
    }
    
    static var operator_11: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_LESS_EQUAL, GDEXTENSION_VARIANT_TYPE_VECTOR4, GDEXTENSION_VARIANT_TYPE_VECTOR4)!
    }()
    
    /// Compares two ``Vector4`` vectors by first checking if the X value of the left vector is less than the X value of the `right` vector. If the X values are exactly equal, then it repeats this check with the Y values of the two vectors, Z values of the two vectors, and then with the W values. This operator is useful for sorting vectors.
    /// 
    /// > Note: Vectors with ``@GDScript.NAN`` elements don't behave the same as other vectors. Therefore, the results from this operator may not be accurate if NaNs are included.
    /// 
    public static func < (lhs: Vector4, rhs: Vector4) -> Bool  {
        var result: Bool = Bool()
        var copy_lhs = lhs
        var copy_rhs = rhs
        
        Vector4.operator_11 (&copy_lhs, &copy_rhs, &result)
        return result
    }
    
    static var operator_12: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_LESS, GDEXTENSION_VARIANT_TYPE_VECTOR4, GDEXTENSION_VARIANT_TYPE_VECTOR4)!
    }()
    
    /// Compares two ``Vector4`` vectors by first checking if the X value of the left vector is less than or equal to the X value of the `right` vector. If the X values are exactly equal, then it repeats this check with the Y values of the two vectors, Z values of the two vectors, and then with the W values. This operator is useful for sorting vectors.
    /// 
    /// > Note: Vectors with ``@GDScript.NAN`` elements don't behave the same as other vectors. Therefore, the results from this operator may not be accurate if NaNs are included.
    /// 
    public static func <= (lhs: Vector4, rhs: Vector4) -> Bool  {
        var result: Bool = Bool()
        var copy_lhs = lhs
        var copy_rhs = rhs
        
        Vector4.operator_12 (&copy_lhs, &copy_rhs, &result)
        return result
    }
    
    static var operator_13: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_GREATER, GDEXTENSION_VARIANT_TYPE_VECTOR4, GDEXTENSION_VARIANT_TYPE_VECTOR4)!
    }()
    
    /// Compares two ``Vector4`` vectors by first checking if the X value of the left vector is greater than the X value of the `right` vector. If the X values are exactly equal, then it repeats this check with the Y values of the two vectors, Z values of the two vectors, and then with the W values. This operator is useful for sorting vectors.
    /// 
    /// > Note: Vectors with ``@GDScript.NAN`` elements don't behave the same as other vectors. Therefore, the results from this operator may not be accurate if NaNs are included.
    /// 
    public static func > (lhs: Vector4, rhs: Vector4) -> Bool  {
        var result: Bool = Bool()
        var copy_lhs = lhs
        var copy_rhs = rhs
        
        Vector4.operator_13 (&copy_lhs, &copy_rhs, &result)
        return result
    }
    
    static var operator_14: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_GREATER_EQUAL, GDEXTENSION_VARIANT_TYPE_VECTOR4, GDEXTENSION_VARIANT_TYPE_VECTOR4)!
    }()
    
    /// Compares two ``Vector4`` vectors by first checking if the X value of the left vector is greater than or equal to the X value of the `right` vector. If the X values are exactly equal, then it repeats this check with the Y values of the two vectors, Z values of the two vectors, and then with the W values. This operator is useful for sorting vectors.
    /// 
    /// > Note: Vectors with ``@GDScript.NAN`` elements don't behave the same as other vectors. Therefore, the results from this operator may not be accurate if NaNs are included.
    /// 
    public static func >= (lhs: Vector4, rhs: Vector4) -> Bool  {
        var result: Bool = Bool()
        var copy_lhs = lhs
        var copy_rhs = rhs
        
        Vector4.operator_14 (&copy_lhs, &copy_rhs, &result)
        return result
    }
    
    static var operator_15: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_ADD, GDEXTENSION_VARIANT_TYPE_VECTOR4, GDEXTENSION_VARIANT_TYPE_VECTOR4)!
    }()
    
    /// Adds each component of the ``Vector4`` by the components of the given ``Vector4``.
    /// 
    public static func + (lhs: Vector4, rhs: Vector4) -> Vector4  {
        var result: Vector4 = Vector4()
        var copy_lhs = lhs
        var copy_rhs = rhs
        
        Vector4.operator_15 (&copy_lhs, &copy_rhs, &result)
        return result
    }
    
    static var operator_16: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_SUBTRACT, GDEXTENSION_VARIANT_TYPE_VECTOR4, GDEXTENSION_VARIANT_TYPE_VECTOR4)!
    }()
    
    /// Subtracts each component of the ``Vector4`` by the components of the given ``Vector4``.
    /// 
    public static func - (lhs: Vector4, rhs: Vector4) -> Vector4  {
        var result: Vector4 = Vector4()
        var copy_lhs = lhs
        var copy_rhs = rhs
        
        Vector4.operator_16 (&copy_lhs, &copy_rhs, &result)
        return result
    }
    
    static var operator_17: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_MULTIPLY, GDEXTENSION_VARIANT_TYPE_VECTOR4, GDEXTENSION_VARIANT_TYPE_VECTOR4)!
    }()
    
    /// Multiplies each component of the ``Vector4`` by the given integer.
    public static func * (lhs: Vector4, rhs: Vector4) -> Vector4  {
        var result: Vector4 = Vector4()
        var copy_lhs = lhs
        var copy_rhs = rhs
        
        Vector4.operator_17 (&copy_lhs, &copy_rhs, &result)
        return result
    }
    
    static var operator_18: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_DIVIDE, GDEXTENSION_VARIANT_TYPE_VECTOR4, GDEXTENSION_VARIANT_TYPE_VECTOR4)!
    }()
    
    /// Divides each component of the ``Vector4`` by the given integer.
    public static func / (lhs: Vector4, rhs: Vector4) -> Vector4  {
        var result: Vector4 = Vector4()
        var copy_lhs = lhs
        var copy_rhs = rhs
        
        Vector4.operator_18 (&copy_lhs, &copy_rhs, &result)
        return result
    }
    
    static var operator_19: GDExtensionPtrOperatorEvaluator = {
        return gi.variant_get_ptr_operator_evaluator (GDEXTENSION_VARIANT_OP_MULTIPLY, GDEXTENSION_VARIANT_TYPE_VECTOR4, GDEXTENSION_VARIANT_TYPE_PROJECTION)!
    }()
    
    /// Multiplies each component of the ``Vector4`` by the given integer.
    public static func * (lhs: Vector4, rhs: Projection) -> Vector4  {
        var result: Vector4 = Vector4()
        var copy_lhs = lhs
        var copy_rhs = rhs
        
        Vector4.operator_19 (&copy_lhs, &copy_rhs, &result)
        return result
    }
    
    /// Enumerated value for the X axis. Returned by ``maxAxisIndex()`` and ``minAxisIndex()``.
    public static let axisX = 0
    /// Enumerated value for the Y axis. Returned by ``maxAxisIndex()`` and ``minAxisIndex()``.
    public static let axisY = 1
    /// Enumerated value for the Z axis. Returned by ``maxAxisIndex()`` and ``minAxisIndex()``.
    public static let axisZ = 2
    /// Enumerated value for the W axis. Returned by ``maxAxisIndex()`` and ``minAxisIndex()``.
    public static let axisW = 3
    /// Zero vector, a vector with all components set to `0`.
    public static let zero = Vector4 (x: 0, y: 0, z: 0, w: 0)
    /// One vector, a vector with all components set to `1`.
    public static let one = Vector4 (x: 1, y: 1, z: 1, w: 1)
    /// Infinity vector, a vector with all components set to ``@GDScript.INF``.
    public static let inf = Vector4 (x: Float.infinity, y: Float.infinity, z: Float.infinity, w: Float.infinity)
}

